export enum Redirect {
  APP = "/app",
  MAIN = "/",
  CONFIRM_CODE = "code",
  CHOOSE = "choose",
  LOGIN = "login",
  SIGN_UP = "signup",
  SETTING = "setting",
  PROFILE = "profile",
  HOME = "home",
  NOTE = "note",
  ARCHIVE = "archive",
  ALARM = "alarm",
  TRASH = "trash",
  SEARCH = "search",
  STOGARE = "stogare",
  FILE = "file",
  UPLOAD = "upload",
  CREATE = "create",
  MOVE = "move",
  GROUP = "group",
  GROUP_STOGARE = "group-stogare",
  OVERVIEW = "overview",
  CALENDAR = "calendar",
  Gemini = "Gemini",
}
